version: "3"

services:
  speedtest:
    build: .
    image: mcre/speedtest:${TAG:-latest}
    ports:
      - "8082:80"
      - "4433:443"
    volumes:
      - .:/var/www/html
    environment:
      - "TZ=Japan"
    restart: always
